[package]
name = "crowd_fund"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet-v1.2.0" }
SupraOracle = { local = "../supra-svalue-feed-framework" }

[addresses]
crowd_fund =  "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"
